### Registro de Bolão 
POST http://localhost:3333/betting-groups
Content-Type: application/json

{
    "name": "Bolão dos Cara",
    "creatorId": "85b11e38-3306-4690-85bb-859f65b6de16"
}

### Consulta de Bolão por Código
GET http://localhost:3333/betting-groups/505KWR